- name: Install Filebeat
  when: ansible_distribution == 'Ubuntu'
  apt:
    name: filebeat

- name: Create directories for Filebeat
  when: ansible_os_family == 'FreeBSD'
  loop:
    - "{{ filebeat.prefix.config }}"
    - "{{ filebeat.config.path.logs }}"
  file:
    state: directory
    path: "{{ item }}"
  notify: Restart Filebeat

- name: Template Filebeat config
  loop:
    - src: filebeat/filebeat.yml
      dest: "{{ filebeat.prefix.config }}/filebeat.yml"
  loop_control:
    label: "{{ item.dest }}"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: o-r
  notify: Restart Filebeat

- name: Configure Filebeat service
  when: ansible_os_family == 'FreeBSD'
  loop:
    - src: rc.conf.d/filebeat
      dest: /usr/local/etc/rc.conf.d/filebeat
  loop_control:
    label: "{{ item.dest }}"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  notify: Restart Filebeat

- name: Enable and start Filebeat
  service:
    name: filebeat
    state: started
    enabled: yes
  register: filebeat_service_start_result
