---
- name: Set up beats repository
  ansible.builtin.include_tasks: repository.yaml
  when: ansible_os_family == 'Debian' and (metricbeat.enabled or filebeat.enabled)

- name: Set up Metricbeat
  ansible.builtin.include_tasks: metricbeat.yaml
  when: metricbeat.enabled

- name: Set up Filebeat
  ansible.builtin.include_tasks: filebeat.yaml
  when: filebeat.enabled
