- name: Install Metricbeat
  when: ansible_distribution == 'Ubuntu'
  apt:
    name: metricbeat

- name: Create directories for Metricbeat
  when: ansible_os_family == 'FreeBSD'
  loop:
    - "{{ metricbeat.prefix.config }}"
    - "{{ metricbeat.config.path.logs }}"
  file:
    state: directory
    path: "{{ item }}"
  notify: Restart Metricbeat

- name: Template Metricbeat config
  loop:
    - src: metricbeat/metricbeat.yml
      dest: "{{ metricbeat.prefix.config }}/metricbeat.yml"
  loop_control:
    label: "{{ item.dest }}"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: o-r
  notify: Restart Metricbeat

- name: Configure Metricbeat service
  when: ansible_os_family == 'FreeBSD'
  loop:
    - src: rc.conf.d/metricbeat.j2
      dest: /usr/local/etc/rc.conf.d/metricbeat
  loop_control:
    label: "{{ item.dest }}"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  notify: Restart Metricbeat

- name: Enable and start Metricbeat
  service:
    name: metricbeat
    state: started
    enabled: yes
  register: metricbeat_service_start_result
