---
- name: Create directories for Metricbeat
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ metricbeat.prefix.config }}"
    - "{{ metricbeat.config.path.logs }}"
  when: ansible_os_family == 'FreeBSD'
  notify: Restart Metricbeat

- name: Template Metricbeat configuration
  template:
    src: "{{ item }}"
    dest: "{{ render_path }}"
    mode: o-r
  loop_control:
    label: "{{ render_path }}"
  vars:
    template_dir: "{{ role_path }}/templates"
    render_path: "{{ metricbeat.prefix.config }}/{{ item|beatsclient_strip_prefix(template_dir + '/metricbeat/')|beatsclient_strip_suffix('.j2') }}"
  with_fileglob:
    - "{{ role_path }}/templates/metricbeat/*.j2"
  notify: Restart Metricbeat

- name: Configure Metricbeat service
  template: src="{{ item.src }}" dest="{{ item.dest }}"
  loop_control:
    label: "{{ item.dest }}"
  with_items:
    - src: rc.conf.d/metricbeat.j2
      dest: /usr/local/etc/rc.conf.d/metricbeat
  when: ansible_os_family == 'FreeBSD'
  notify: Restart Metricbeat

- name: Enable Metricbeat service
  lineinfile: path="{{ item.path }}" regexp="{{ item.regexp }}" line="{{ item.line }}"
  loop_control:
    label: "{{ item.path }}"
  with_items:
    - path: /etc/rc.conf
      regexp: "^metricbeat_enable="
      line: 'metricbeat_enable="YES"'
  when: ansible_os_family == 'FreeBSD'
  notify:
    - Start Metricbeat
