---
- name: Install Metricbeat
  when: ansible_os_family == 'Debian'
  ansible.builtin.apt:
    name: metricbeat
    update_cache: yes

- name: Create directories for Metricbeat
  when: ansible_os_family == 'FreeBSD'
  loop:
    - "{{ metricbeat.prefix.config }}"
    - "{{ metricbeat.config.path.logs }}"
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    owner: root
    mode: "0755"
  notify: Restart Metricbeat

- name: Template Metricbeat config
  ansible.builtin.template:
    src: metricbeat/metricbeat.yml
    dest: "{{ metricbeat.prefix.config }}/metricbeat.yml"
    mode: o-r
    owner: root
  notify: Restart Metricbeat

- name: Configure Metricbeat service
  when: ansible_os_family == 'FreeBSD'
  ansible.builtin.template:
    src: rc.conf.d/metricbeat.j2
    dest: /usr/local/etc/rc.conf.d/metricbeat
    owner: root
    mode: "0755"
  notify: Restart Metricbeat

- name: Enable and start Metricbeat
  ansible.builtin.service:
    name: metricbeat
    state: started
    enabled: yes
  egister: metricbeat_service_start_result
