- name: Restart Metricbeat
  service:
    name: metricbeat
    state: restarted
  when: not metricbeat_service_start_result.changed|default(false)

- name: Restart Filebeat
  service:
    name: filebeat
    state: restarted
  when: not filebeat_service_start_result.changed|default(false)
