---
- name: Converge
  hosts: all
  vars:
    metricbeat:
      enabled: yes
    filebeat:
      enabled: yes
  environment:
    GITHUB_ACTIONS: "maybe"
  tasks:
    - name: "Include ansible-proserver-beats"
      ansible.builtin.include_role:
        name: "ansible-proserver-beats"
